### ISSUE TITLE
Nitpicking variables restic_client_user  and restic_client_group are not used consistently

### ISSUE THREAD

**Issue by nklamann** [FIFTY2Technology/ansible-role-restic_client#2]
For example not in 
https://github.com/FIFTY2Technology/ansible-role-restic_client/blob/main/templates/restic-prune.service.j2

and might be in other  places 
Oversight or planned ?

**Comment by eliba** [comment]
Hey, thanks for raising this issue! It was an oversight indeed, I will fix it.

**Comment by eliba** [comment]
fixed with https://github.com/FIFTY2Technology/ansible-role-restic_client/commit/e66c1f44ca85568ef61675f96b27da0da4c2e851
